# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
#source 'https://github.com/CocoaPods/Specs.git'


target 'LivenessCloudSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'LivenessCloud' ,:git => 'https://github.com/trungnguyen1791/LivenessCloudPOD.git'
  pod 'QTSCardReader' ,:git => 'https://github.com/trungnguyen1791/QTSCardReader.git'
  pod 'SVProgressHUD'
  pod 'FlashLiveness', :git => 'https://github.com/stevienguyen1988/FlashLivenessPod.git'
  # Pods for LivenessCloudSample
  
  target 'LivenessCloudSampleTests' do
    inherit! :search_paths
  end

  target 'LivenessCloudSampleUITests' do
    # Pods for testing
  end

end
post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
            xcconfig_path = config.base_configuration_reference.real_path
            xcconfig = File.read(xcconfig_path)
            xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
            File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
            end
        end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
    end
  end
end
#post_install do |installer|
#      installer.pods_project.targets.each do |target|
#          target.build_configurations.each do |config|
#          xcconfig_path = config.base_configuration_reference.real_path
#          xcconfig = File.read(xcconfig_path)
#          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
#          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
#          end
#      end
#  end
